# app2-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - name: app2
        image: node:14
        command: ["node", "app_2.js"]
        ports:
        - containerPort: 3000
        env:
        - name: APP1_SERVICE_HOST
          value: "app1-service"

---
apiVersion: v1
kind: Service
metadata:
  name: app2-service
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8006
      targetPort: 3000
