# app1-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app1
  namespace: my-namespace
spec:
  replicas: 2
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - name: app1
        image: node:14
        command: ["node", "app.js"]
        ports:
        - containerPort: 3000
        env:
        - name: APP2_SERVICE_HOST
          value: "app2-service"

---
apiVersion: v1
kind: Service
metadata:
  name: app1-service
spec:
  selector:
    app: app1
  ports:
    - protocol: TCP
      port: 8005
      targetPort: 3000
