apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: superbotdevops/sbt-app-frontend:a738359
          ports:
            - containerPort: 3000
      imagePullSecrets:
        - name: dockerhub-secret  # Name of the Docker Hub secret
