apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-namespace
spec:
  replicas: 50
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: superbotdevops/my-app:3d84367
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret  # Name of the Docker Hub secret
