apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: my-namespace
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: superbotdevops/sbt-app-frontend:1388e75
          ports:
            - containerPort: 8000
      imagePullSecrets:
        - name: dockerhub-secret  # Name of the Docker Hub secret
