apiVersion: v1
kind: Secret
metadata:
  name: dockerhub-secret
  namespace: my-namespace
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJzdXBlcmJvdGRldm9wcyIsInBhc3N3b3JkIjoiYkQuelBxd0dqeUcucEw2IiwicmVhbG1zIjoiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIn19fQ==
type: kubernetes.io/dockerconfigjson
