apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: my-namespace
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 9005
      targetPort: 8080
  type: LoadBalancer
  externalTrafficPolicy: Local
  healthCheckNodePort: 8080  # Health check port matches the container port
